- name: Ensure Wordpress directory exists
  file:
    path: /opt/wordpress
    state: directory
    mode: "0755"

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ wordpress_site_dir }}/docker-compose.yml"
    mode: "0644"

# using shell is not idempotent, use community.docker.docker-compose
- name: Launch Wordpress using Docker Compose
  shell: docker-compose up -d
  args:
    chdir: /opt/wordpress
