# - name: Ensure Docker is installed
#   apt:
#     name: docker.io
#     state: present
#     update_cache: true
#   become: true
#
# - name: Ensure Docker Compose is installed
#   get_url:
#     url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
#     dest: /usr/local/bin/docker-compose
#     mode: "0755"
#   become: true

- name: Create target directory
  file:
    path: /opt/inception
    state: directory
    mode: "0755"

- name: Copy Makefile
  copy:
    src: Makefile
    dest: /opt/inception/Makefile
    mode: "0755"
# COPY THE ENTIRE FOLDER

- name: Run Local Inception
  command: make all
  args:
    chdir: /opt/inception
  become: true
