- name: Ensure Wordpress directory exists
  file:
    path: "{{ wordpress_site_dir }}"
    state: directory
    mode: "0755"

- name: Copy .env file
  copy:
    src: .env
    dest: "{{ wordpress_site_dir }}/.env"
    mode: "0600"

- name: Create directory for TLS certificates
  file:
    path: "{{ wordpress_site_dir }}/certs"
    state: directory
    mode: "0755"

- name: Generate private key
  openssl_privatekey:
    path: "{{ wordpress_site_dir }}/certs/privkey-{{ domain }}.pem"
    size: 2048
    type: RSA

- name: Generate self-signed certificate
  openssl_certificate:
    path: "{{ wordpress_site_dir }}/certs/fullchain-{{ domain }}.pem"
    privatekey_path: "{{ wordpress_site_dir }}/certs/privkey-{{ domain }}.pem"
    provider: selfsigned

- name: Template nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{ wordpress_site_dir }}/nginx.conf"
    mode: "0644"

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ wordpress_site_dir }}/docker-compose.yml"
    mode: "0644"

- name: Launch Wordpress using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ wordpress_site_dir }}"
    state: present
