- name: Load launched host IPs and add them to inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load launched host data
      include_vars:
        file: "../launched_hosts.yml"

    - name: Add launched hosts to dynamic group
      add_host:
        name: "{{ item.ansible_host }}"
        groups: launched
        ansible_user: "{{ item.ansible_user }}"
        ansible_ssh_private_key_file: "{{ item.ansible_ssh_private_key_file }}"
      loop: "{{ launched_hosts }}"

- name: Deploy Inception
  hosts: launched
  become: true
  tasks:
    - name: Include main tasks from Inception role
      include_role:
        name: inception
        tasks_from: main
