- name: Terminate EC2 instance
  hosts: localhost
  gather_facts: true
  vars_files:
    - ../vars/remote_vault_vars.yml
  tasks:
    - name: Load instance IDs from file
      include_vars:
        file: "../.launched_instance_metadata.yml"

    - name: Terminate instance(s)
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ launched_instance_ids }}"
        state: absent
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_DEFAULT_REGION: "{{ aws_default_region }}"

    - name: Delete launched_instance_metadata.yml
      file:
        path: "../.launched_instance_metadata.yml"
        state: absent
