- name: Terminate EC2 instance
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Terminate instance(s)
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ launched_instance_ids }}"
        state: absent
